[package]
name = "vrt_buffer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdal = {version = "0.15.0", features = ["bindgen"]}
bindgen = "0.66.1"
ndarray = "0.15.6"
